/*  Persistence of Vision Ray Tracer version 3.7 Include File
    File: mkstones.inc
    Author: Matt Kukla <matt.kukla@yandex.ru>
    Last updated: May 2021
    Description: A collection of additional stone textures for POV-Ray.  
    Includes all mkstone files.
*/

#ifndef(MKStones_Inc)
#declare MKStones_Inc = version;

#version 3.7;

#ifdef(View_POV_Include_Stack)
    #debug "including mkstones.inc\n"
#end

#include "mkstones1.inc"

#end
